### ISSUE TITLE
oauthlib Missing access token parameter.

### ISSUE THREAD

**Issue by mb132** [bloodywing/plentyrest#2]
Hallo,

erst einmal vielen Dank für diesen REST-Client.

Leider bekomme ich folgende Fehlermeldungen:

```python
plenty = Plenty(resturl, restuser, restpasswd)
```

```python
Traceback (most recent call last):
  File "C:/Project/rest_test.py", line 62, in <module>
    plenty = Plenty(resturl, restuser, restpasswd)
  File "C:\Project\plentyrest\rest.py", line 36, in __init__
    password=password)
  File "C:\Project\venv\lib\site-packages\requests_oauthlib\oauth2_session.py", line 306, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "C:\Project\venv\lib\site-packages\oauthlib\oauth2\rfc6749\clients\base.py", line 415, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "C:\Project\venv\lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 425, in parse_token_response
    validate_token_parameters(params)
  File "C:\Project\venv\lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 435, in validate_token_parameters
    raise MissingTokenError(description="Missing access token parameter.")
oauthlib.oauth2.rfc6749.errors.MissingTokenError: (missing_token) Missing access token parameter.
```

Hast du eine woran das liegen könnte?

Beste Grüße

**Comment by bloodywing** [comment]
Eventuell hat Plenty wieder den Name vom access token geändert. Ursprünglich war es AccessToken (was nicht rfc6749 konform ist).
Öffne mal `C:\Project\venv\lib\site-packages\oauthlib\oauth2\rfc6749\clients\base.py` und lass dir vor Zeile 415 den body ausgeben. Mit print oder so.

Eventuell stimmen deine Login Daten auch nicht.
Du kannst mein Repo gerne forken, ich habe keinen Plenty Account mehr und kann weder testen noch groß daran weiter entwickeln.
